import unittest

from container import Move, Row, Direction
from rule import RenjuRule


def parse_board(board_string: str):
    return [[None if c == '.' else False if c == 'O' else True for c in r.strip()] for r in board_string.strip().splitlines()]


class RuleTest(unittest.TestCase):
    renju = RenjuRule()

    def test_get_rows1(self):
        board_string = '''
            ...............
            ...............
            ...............
            ....O.....O....
            .....O...O.....
            ......O........
            .....O.OOO.....
            .......O.......
            .....O.O.O.....
            ....O..........
            ...O...........
            ...............
            ...............
            ...............
            ...............
        '''
        board = parse_board(board_string)
        move = Move(6, 7, False)
        threes, fours = self.renju.get_rows(board, move)
        self.assertEqual((len(threes), len(fours)), (3, 3))

    def test_is_explicitly_closed_three(self):
        def assert_explicitly_closed(move_list, inner_blank, direction, result):
            self.assertEqual(self.renju.is_explicitly_closed_three(board, Row(move_list, inner_blank, direction), False), result)

        board_string = '''
            ...............
            .......X.OO.O.X
            ...............
            ....O.....O....
            .....O...O.....
            ......O........
            .....O.OOO.....
            .......O.......
            .....O.O.O.....
            ....O..........
            ...O...X.OOO.X.
            ...........OOO.
            ...OO.OX....O..
            .....O.OOO.O...
            ...............
        '''
        board = parse_board(board_string)

        assert_explicitly_closed([(6, 7), (6, 8), (6, 9)], None, Direction(0, 1), True)
        assert_explicitly_closed([(6, 7), (7, 7), (8, 7)], None, Direction(1, 0), False)
        assert_explicitly_closed([(12, 3), (12, 4), (12, 6)], (12, 5), Direction(0, 1), True)
        assert_explicitly_closed([(13, 7), (13, 8), (13, 9)], None, Direction(0, 1), True)
        assert_explicitly_closed([(13, 11), (12, 12), (11, 13)], None, Direction(-1, 1), True)
        assert_explicitly_closed([(11, 11), (11, 12), (11, 13)], None, Direction(0, 1), False)
        assert_explicitly_closed([(10, 9), (10, 10), (10, 11)], None, Direction(0, 1), True)
        assert_explicitly_closed([(1, 9), (1, 10), (1, 12)], (1, 11), Direction(0, 1), False)


if __name__ == '__main__':
    unittest.main()
